/**
 * populate-queue.js
 * Adds all PLAN2.md topics to the autopilot topic-queue.json.
 * Preserves existing entries. Skips duplicates by slug.
 * Run: node populate-queue.js
 */

const fs = require('fs');
const path = require('path');

const QUEUE_FILE = path.join(__dirname, 'autopilot', 'topic-queue.json');
const existing = JSON.parse(fs.readFileSync(QUEUE_FILE, 'utf8'));
const existingSlugs = new Set(existing.map(t => t.slug));

let idCounter = existing.length + 1;
function mkId() { return 'auto-' + String(idCounter++).padStart('3', '0'); }

// ── All topics from PLAN2.md ──────────────────────────────────────────────────
const NEW_TOPICS = [

  // A. HIDDEN GOVERNMENT / BLACK BUDGET / OPS
  { slug: 'raven-rock',            title: 'Raven Rock Mountain Complex (Site R)',       section: 'Hidden Government', mapBadge: 'Deep State',  keywords: ['COG','continuity of government','nuclear bunker','Site R','Raven Rock'], relatedSlugs: ['mount-weather','cheyenne-mountain','shadow-government','fema'] },
  { slug: 'mount-weather',         title: 'Mount Weather Emergency Operations Center',  section: 'Hidden Government', mapBadge: 'Deep State',  keywords: ['COG','continuity of government','FEMA','shadow government','nuclear bunker'], relatedSlugs: ['raven-rock','cheyenne-mountain','fema','shadow-government'] },
  { slug: 'cheyenne-mountain',     title: 'Cheyenne Mountain — NORAD Underground Fortress', section: 'Hidden Government', mapBadge: 'Deep State', keywords: ['NORAD','nuclear bunker','deep state','underground base','DUMB'], relatedSlugs: ['raven-rock','mount-weather','dumbs','shadow-government'] },
  { slug: 'greenbrier-bunker',     title: 'Greenbrier Congressional Bunker',            section: 'Hidden Government', mapBadge: 'Deep State',  keywords: ['COG','congress','bunker','continuity of government','cold war'], relatedSlugs: ['raven-rock','mount-weather','shadow-government'] },
  { slug: 'continuity-of-government', title: 'Continuity of Government (COG) Programs', section: 'Hidden Government', mapBadge: 'Deep State', keywords: ['COG','shadow government','FEMA','executive orders','martial law'], relatedSlugs: ['fema','raven-rock','mount-weather','shadow-government','sealed-indictments'] },
  { slug: 'project-stargate',      title: 'Project Stargate — CIA Remote Viewing Program', section: 'Hidden Government', mapBadge: 'Intelligence', keywords: ['remote viewing','CIA','psychic spy','SRI','Ingo Swann'], relatedSlugs: ['remote-viewing','cia-operations','mkultra','five-eyes'] },
  { slug: 'project-bluebird',      title: 'Project Bluebird — CIA Behavior Modification', section: 'Hidden Government', mapBadge: 'Intelligence', keywords: ['CIA','mind control','behavior modification','ARTICHOKE','MKUltra precursor'], relatedSlugs: ['mkultra','cia-operations','super-soldiers','monarch'] },
  { slug: 'operation-gladio',      title: 'Operation Gladio — NATO Stay-Behind Terror Networks', section: 'Hidden Government', mapBadge: 'Intelligence', keywords: ['NATO','stay-behind','false flag','terrorism','Operation Gladio','Italy'], relatedSlugs: ['false-flags','cia-operations','operation-northwoods','shadow-government'] },
  { slug: 'operation-chaos',       title: 'Operation CHAOS — CIA Domestic Surveillance 1967–74', section: 'Hidden Government', mapBadge: 'Intelligence', keywords: ['CIA','domestic surveillance','antiwar movement','COINTELPRO','Operation CHAOS'], relatedSlugs: ['cointelpro','cia-operations','operation-mockingbird','nsa-surveillance'] },
  { slug: 'echelon',               title: 'ECHELON — Five Eyes Mass Interception Network', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['ECHELON','Five Eyes','mass surveillance','signals intelligence','NSA'], relatedSlugs: ['five-eyes','nsa-surveillance','global-surveillance-grid','raf-menwith-hill'] },
  { slug: 'total-information-awareness', title: 'Total Information Awareness — DARPA Surveillance Blueprint', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['DARPA','TIA','mass surveillance','John Poindexter','pre-crime'], relatedSlugs: ['nsa-surveillance','ai-surveillance','five-eyes','prism-expansion'] },
  { slug: 'main-core-database',    title: 'Main Core — The List of Americans to Detain', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['Main Core','detention list','COG','martial law','shadow government'], relatedSlugs: ['fema','shadow-government','continuity-of-government','nsa-surveillance'] },
  { slug: 'darpa-social-mapping',  title: 'DARPA Social Network Mapping Programs',      section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['DARPA','social network analysis','mass surveillance','LifeLog','Facebook'], relatedSlugs: ['facebook-google-surveillance','ai-surveillance','nsa-surveillance','transhumanism'] },
  { slug: 'in-q-tel',              title: "In-Q-Tel — CIA's Venture Capital Arm",       section: 'Hidden Government', mapBadge: 'Intelligence', keywords: ['In-Q-Tel','CIA','Silicon Valley','venture capital','surveillance capitalism'], relatedSlugs: ['cia-operations','facebook-google-surveillance','ai-surveillance','nsa-surveillance'] },
  { slug: 'room-641a',             title: 'Room 641A — AT&T NSA Splitter Cabinet',       section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['Room 641A','NSA','AT&T','internet surveillance','Mark Klein'], relatedSlugs: ['nsa-surveillance','five-eyes','echelon','prism-expansion'] },
  { slug: 'carnivore-surveillance', title: 'Carnivore — FBI Packet-Sniffing Program',   section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['Carnivore','FBI','packet sniffing','internet surveillance','DCS1000'], relatedSlugs: ['nsa-surveillance','prism-expansion','five-eyes','snowden-assange'] },
  { slug: 'prism-expansion',       title: 'PRISM Expansion — Beyond Snowden Documents', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['PRISM','NSA','Snowden','mass surveillance','tech companies'], relatedSlugs: ['nsa-surveillance','snowden-assange','five-eyes','facebook-google-surveillance'] },
  { slug: 'fusion-centers',        title: 'Fusion Centers — DHS Intelligence Fusion',   section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['fusion centers','DHS','local police','surveillance','counter-terrorism'], relatedSlugs: ['nsa-surveillance','predictive-policing','ai-surveillance','shadow-government'] },
  { slug: 'stingray-devices',      title: 'Stingray / IMSI Catchers — Mass Cell Tracking', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['Stingray','IMSI catcher','cell phone tracking','law enforcement','Harris Corporation'], relatedSlugs: ['nsa-surveillance','5g-surveillance','rfid-surveillance','ai-surveillance'] },
  { slug: 'predictive-policing',   title: 'Predictive Policing — Pre-Crime Algorithms', section: 'Hidden Government', mapBadge: 'Surveillance', keywords: ['predictive policing','pre-crime','PredPol','algorithmic bias','surveillance'], relatedSlugs: ['ai-surveillance','palantir-gotham','stingray-devices','social-media-control'] },

  // B. ANCIENT CIVILISATIONS / HIDDEN HISTORY
  { slug: 'doggerland',            title: 'Doggerland — The Flooded North Sea Civilisation', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Doggerland','North Sea','flooded civilisation','Mesolithic','Younger Dryas'], relatedSlugs: ['younger-dryas-impact','atlantis-lemuria-mu','sundaland','mud-flood'] },
  { slug: 'sundaland',             title: 'Sundaland — The Submerged Southeast Asian Continent', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Sundaland','Sunda shelf','submerged continent','Lemuria','ancient civilisation'], relatedSlugs: ['doggerland','atlantis-lemuria-mu','younger-dryas-impact','gunung-padang'] },
  { slug: 'richat-atlantis',       title: 'Richat Structure — Atlantis in Mauritania',   section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Richat Structure','Eye of Africa','Atlantis','Mauritania','Plato'], relatedSlugs: ['atlantis-lemuria-mu','younger-dryas-impact','piri-reis-map','giza-complex'] },
  { slug: 'yonaguni-monument',     title: 'Yonaguni Monument — Japan\'s Underwater Pyramid', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Yonaguni','underwater pyramid','Japan','ancient ruins','Masaaki Kimura'], relatedSlugs: ['atlantis-lemuria-mu','bimini-road','ancient-alien-ruins','sundaland'] },
  { slug: 'bimini-road',           title: 'Bimini Road — Bahamas Underwater Stone Formation', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Bimini Road','Bahamas','underwater ruins','Edgar Cayce','Atlantis'], relatedSlugs: ['atlantis-lemuria-mu','yonaguni-monument','richat-atlantis','younger-dryas-impact'] },
  { slug: 'dwarka-submerged',      title: 'Dwarka — Submerged Ancient City off India',   section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Dwarka','submerged city','India','Krishna','ancient archaeology'], relatedSlugs: ['atlantis-lemuria-mu','yonaguni-monument','vimanas','the-vedas'] },
  { slug: 'baalbek-megaliths',     title: 'Baalbek — 1,500-Ton Stones No Modern Crane Can Lift', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Baalbek','megaliths','Lebanon','ancient construction','impossible engineering'], relatedSlugs: ['sacsayhuaman','ancient-alien-ruins','annunaki','gobekli-tepe-burial','vimanas'] },
  { slug: 'sacsayhuaman',          title: 'Sacsayhuamán — Precision-Cut Masonry Impossible by Hand', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Sacsayhuaman','Inca','precision masonry','ancient technology','Peru'], relatedSlugs: ['baalbek-megaliths','ancient-alien-ruins','annunaki','nazca-lines','puma-punku'] },
  { slug: 'nan-madol',             title: 'Nan Madol — Island City Built on Coral',      section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Nan Madol','Micronesia','ancient city','coral','impossible engineering'], relatedSlugs: ['baalbek-megaliths','ancient-alien-ruins','yonaguni-monument','sacsayhuaman'] },
  { slug: 'derinkuyu',             title: 'Derinkuyu Underground City — 18 Levels, 20,000 People', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Derinkuyu','underground city','Turkey','Cappadocia','ancient shelter'], relatedSlugs: ['dumbs','honeycomb-earth','ancient-alien-ruins','baalbek-megaliths','gobekli-tepe-burial'] },
  { slug: 'gobekli-tepe-burial',   title: 'Göbekli Tepe Burial Mystery — Why Was It Buried?', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Gobekli Tepe','deliberately buried','ancient mystery','Klaus Schmidt','pre-flood'], relatedSlugs: ['ancient-alien-ruins','younger-dryas-impact','atlantis-lemuria-mu','annunaki'] },
  { slug: 'younger-dryas-impact',  title: 'Younger Dryas Impact — The Comet That Reset Civilisation', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Younger Dryas','comet impact','civilisation reset','Randall Carlson','Graham Hancock'], relatedSlugs: ['atlantis-lemuria-mu','gobekli-tepe-burial','mud-flood','tartaria','great-solar-flash'] },
  { slug: 'library-of-alexandria', title: 'Lost Library of Alexandria — What Was Actually Destroyed', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Library of Alexandria','ancient knowledge','destruction','Julius Caesar','Hypatia'], relatedSlugs: ['stolen-history','tartaria','ancient-alien-ruins','the-vedas','oopart'] },
  { slug: 'osireion-abydos',       title: 'Osireion at Abydos — Pre-Dynastic Temple in Groundwater', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Osireion','Abydos','Egypt','pre-dynastic','submerged temple'], relatedSlugs: ['giza-complex','ancient-alien-ruins','atlantis-lemuria-mu','annunaki'] },
  { slug: 'gunung-padang',         title: 'Gunung Padang — 25,000-Year-Old Pyramid in Indonesia', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Gunung Padang','Indonesia','ancient pyramid','25000 years','Danny Natawidjaja'], relatedSlugs: ['younger-dryas-impact','sundaland','ancient-alien-ruins','gobekli-tepe-burial'] },
  { slug: 'vitrified-forts',       title: 'Vitrified Forts — Scottish Hillforts Melted by Unknown Heat', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['vitrified forts','Scotland','ancient fire','impossible heat','megalithic'], relatedSlugs: ['mahabharata-nuclear-war','vimanas','younger-dryas-impact','ancient-alien-ruins'] },
  { slug: 'klerksdorp-spheres',    title: 'Klerksdorp Spheres — 3-Billion-Year-Old Machined Metal Objects', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Klerksdorp spheres','South Africa','OOPArts','out of place artifacts','ancient technology'], relatedSlugs: ['oopart','ancient-alien-ruins','annunaki','ancient-builder-race'] },
  { slug: 'paracas-skulls',        title: 'Paracas Skull DNA — Non-Human Mitochondrial Results', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Paracas skulls','elongated skulls','DNA','non-human','Peru','Brien Foerster'], relatedSlugs: ['pre-adamites','homocapensis','giants-suppressed','annunaki','atacama-humanoid'] },
  { slug: 'bosnian-pyramids',      title: 'Bosnian Pyramid Controversy — Semir Osmanagic Excavations', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Bosnian pyramids','Semir Osmanagic','Visoko','ancient structures','covered pyramids'], relatedSlugs: ['ancient-alien-ruins','giza-complex','gunung-padang','younger-dryas-impact'] },
  { slug: 'sanxingdui',            title: 'Sanxingdui Bronzes — Bronze Age China with No Known Origin', section: 'Ancient History', mapBadge: 'Ancient', keywords: ['Sanxingdui','Bronze Age China','unknown civilisation','alien artefacts','Sichuan'], relatedSlugs: ['ancient-alien-ruins','chinese-pyramids','annunaki','oopart'] },

  // C. UFO / SPECIFIC INCIDENTS
  { slug: 'phoenix-lights',        title: 'Phoenix Lights 1997 — Mile-Wide Craft, 10,000 Witnesses', section: 'UFO Incidents', mapBadge: 'UFO',     keywords: ['Phoenix Lights','1997','Arizona','UFO sighting','Fife Symington'], relatedSlugs: ['ufo-disclosure','tr3b-arvs','majestic-mj12','battle-of-la-1942'] },
  { slug: 'rendlesham-forest',     title: "Rendlesham Forest 1980 — UK's Roswell, Binary Code Download", section: 'UFO Incidents', mapBadge: 'UFO',   keywords: ['Rendlesham Forest','1980','UK','UFO landing','Jim Penniston','binary code'], relatedSlugs: ['ufo-disclosure','majestic-mj12','area-51','five-eyes'] },
  { slug: 'varginha-brazil',       title: 'Varginha Brazil 1996 — ET Captured by Military',   section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Varginha','Brazil','1996','ET captured','military','UFO crash'], relatedSlugs: ['ufo-disclosure','greys-nordics-ebes','majestic-mj12','battle-of-la-1942'] },
  { slug: 'ariel-school',          title: 'Ariel School Zimbabwe 1994 — 62 Children, Same ET Description', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Ariel School','Zimbabwe','1994','children','ET contact','John Mack'], relatedSlugs: ['ufo-disclosure','greys-nordics-ebes','blue-avians','pleiadian-guidance'] },
  { slug: 'roswell-witnesses',     title: 'Roswell Witnesses — 600+ Affidavits Never Covered Together', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Roswell','1947','witness affidavits','UFO crash','Jesse Marcel'], relatedSlugs: ['majestic-mj12','area-51','ufo-disclosure','battle-of-la-1942'] },
  { slug: 'foo-fighters-wwii',     title: 'Foo Fighters WWII — Allied and Axis Pilots, Same Craft',   section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['foo fighters','WWII','UFO','Allied pilots','Axis pilots'], relatedSlugs: ['battle-of-la-1942','ufo-disclosure','tr3b-arvs','nazi-breakaway-group'] },
  { slug: 'kecksburg',             title: 'Kecksburg Incident 1965 — Acorn-Shaped Craft, Soviet/NASA Link', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Kecksburg','1965','UFO crash','Pennsylvania','acorn-shaped craft'], relatedSlugs: ['roswell-witnesses','ufo-disclosure','operation-paperclip','nasa-deceptions'] },
  { slug: 'hessdalen-lights',      title: 'Hessdalen Lights — 40-Year Anomaly in Norway',          section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Hessdalen lights','Norway','anomalous lights','scientific study','plasma'], relatedSlugs: ['ufo-disclosure','haarp','firmament','bermuda-triangle'] },
  { slug: 'westall-1966',          title: 'Westall 1966 — 200 Australian Schoolchildren, Mass Sighting', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Westall 1966','Australia','schoolchildren','UFO mass sighting','Melbourne'], relatedSlugs: ['ufo-disclosure','ariel-school','pine-gap','five-eyes'] },
  { slug: 'malmstrom-missiles',    title: 'Malmstrom Missile Shutdown — ICBMs Disabled by UFO',    section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Malmstrom','ICBM','UFO','nuclear missiles disabled','1967','Robert Salas'], relatedSlugs: ['ufo-disclosure','majestic-mj12','solar-warden','scalar-weapons'] },
  { slug: 'tunguska-exotic',       title: 'Tunguska Exotic Hypotheses — Tesla Weapon or ET Craft?', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Tunguska','1908','Tesla weapon','ET craft','explosion','Siberia'], relatedSlugs: ['scalar-weapons','haarp','ufo-disclosure','antigravity'] },
  { slug: 'nuremberg-1561',        title: 'Nuremberg 1561 Sky Battle — Woodcut Broadsheet UFO Battle', section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Nuremberg 1561','sky battle','UFO history','woodcut','ancient UFO'], relatedSlugs: ['foo-fighters-wwii','ufo-disclosure','ancient-alien-ruins','vimanas'] },
  { slug: 'project-blue-book',     title: 'Project Blue Book — 12,618 Cases, 701 Unexplained',    section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Project Blue Book','USAF','UFO investigation','J. Allen Hynek','unexplained cases'], relatedSlugs: ['ufo-disclosure','majestic-mj12','roswell-witnesses','tic-tac-origins'] },
  { slug: 'tic-tac-origins',       title: 'Tic Tac Craft Origins — USS Nimitz 2004',               section: 'UFO Incidents', mapBadge: 'UFO', keywords: ['Tic Tac UFO','USS Nimitz','2004','David Fravor','UAP'], relatedSlugs: ['ufo-disclosure','tr3b-arvs','solar-warden','majestic-mj12'] },
  { slug: 'hollow-moon',           title: 'Hollow Moon Theory — Seismological Evidence from Apollo', section: 'UFO Incidents', mapBadge: 'Space', keywords: ['hollow moon','Apollo seismology','moon bell','artificial satellite','lunar anomalies'], relatedSlugs: ['moon-truth','moon-structures','moonlanding-hoax','nasa-deceptions'] },

  // D. ELITE POWER NETWORKS
  { slug: 'davos-meetings',        title: 'Davos / WEF Annual Meetings — What Is Actually Decided', section: 'Elite Networks', mapBadge: 'Power',  keywords: ['Davos','WEF','World Economic Forum','Klaus Schwab','global governance'], relatedSlugs: ['wef-schwab','great-reset','bilderberg','council-foreign-relations'] },
  { slug: 'bohemian-grove-guests', title: 'Bohemian Grove Guest Lists — Who Was Photographed There', section: 'Elite Networks', mapBadge: 'Power', keywords: ['Bohemian Grove','guest list','Nixon','Reagan','Skull and Bones'], relatedSlugs: ['bohemian-grove','skull-bones','bilderberg','cia-operations'] },
  { slug: 'bilderberg-leaks',      title: 'Bilderberg Leaks — Agendas and Attendees Over 70 Years', section: 'Elite Networks', mapBadge: 'Power', keywords: ['Bilderberg','leaked agenda','attendees','Tony Blair','Henry Kissinger'], relatedSlugs: ['bilderberg','council-foreign-relations','trilateral-commission','committee-300'] },
  { slug: 'rhodes-scholars',       title: 'Rhodes Scholars — The Network Placing Globalists in Government', section: 'Elite Networks', mapBadge: 'Power', keywords: ['Rhodes Scholars','Cecil Rhodes','globalism','Rhodes Trust','Clinton'], relatedSlugs: ['council-foreign-relations','trilateral-commission','new-world-order','skull-bones'] },
  { slug: 'think-tank-capture',    title: 'Think Tank Capture — How Policy Is Laundered Through Academia', section: 'Elite Networks', mapBadge: 'Power', keywords: ['think tanks','policy laundering','CFR','Brookings','RAND Corporation'], relatedSlugs: ['council-foreign-relations','corporate-state-capture','operation-mockingbird','educational-indoctrination'] },
  { slug: 'ngo-soft-power',        title: 'NGO Soft Power — Regime Change via Civil Society',       section: 'Elite Networks', mapBadge: 'Power', keywords: ['NGO','NED','USAID','regime change','Open Society','George Soros'], relatedSlugs: ['george-soros','cia-operations','hegelian-dialectic','corporate-state-capture'] },
  { slug: 'offshore-trust-havens', title: 'Offshore Trust Havens — Legal Structures Hiding Trillions', section: 'Elite Networks', mapBadge: 'Finance', keywords: ['offshore trusts','tax havens','wealth hiding','Cayman Islands','Panama'], relatedSlugs: ['panama-papers','rothschilds','blackrock-vanguard','world-gold-heist','city-of-london'] },
  { slug: 'panama-papers',         title: 'Panama Papers Networks — Who Was In Them and Why It Was Buried', section: 'Elite Networks', mapBadge: 'Finance', keywords: ['Panama Papers','Mossack Fonseca','offshore tax evasion','elite wealth','ICIJ'], relatedSlugs: ['offshore-trust-havens','rothschilds','george-soros','world-gold-heist'] },
  { slug: 'private-island-meetings', title: 'Private Island Meetings — The Unrecorded Gatherings',  section: 'Elite Networks', mapBadge: 'Power', keywords: ['private islands','elite meetings','Epstein island','unrecorded summits'], relatedSlugs: ['epstein-network','bohemian-grove','bilderberg','skull-bones'] },

  // E. TECH / AI / NEXT-GEN CONTROL
  { slug: 'ai-narrative-manipulation', title: 'AI Narrative Manipulation — LLMs Trained to Steer Opinion', section: 'Technology Control', mapBadge: 'Technology', keywords: ['AI','LLM','narrative control','opinion steering','ChatGPT','censorship'], relatedSlugs: ['social-media-control','operation-mockingbird','dead-internet-theory','deepfake-politics'] },
  { slug: 'synthetic-influencers', title: 'Synthetic Influencers — AI-Generated Social Media Personalities', section: 'Technology Control', mapBadge: 'Technology', keywords: ['synthetic influencers','AI','virtual influencers','fake personas','astroturfing'], relatedSlugs: ['social-media-control','dead-internet-theory','ai-narrative-manipulation','deepfake-politics'] },
  { slug: 'deepfake-politics',     title: 'Deepfake Politics — Political Deepfakes Already Deployed', section: 'Technology Control', mapBadge: 'Technology', keywords: ['deepfakes','political manipulation','video forgery','AI video','disinformation'], relatedSlugs: ['ai-narrative-manipulation','social-media-control','predictive-programming','false-flags'] },
  { slug: 'vehicle-kill-switches', title: 'Vehicle Kill Switches — 2026 Federal Mandate, All New Cars',   section: 'Technology Control', mapBadge: 'Technology', keywords: ['vehicle kill switch','remote shutdown','NHTSA','Infrastructure Act','control'], relatedSlugs: ['smart-cities','cbdc','rfid-surveillance','5g-surveillance'] },
  { slug: 'emotion-recognition',   title: 'Emotion Recognition Cameras — Airport and Retail Deployments', section: 'Technology Control', mapBadge: 'Technology', keywords: ['emotion recognition','facial AI','airport surveillance','retail tracking','biometrics'], relatedSlugs: ['ai-surveillance','smart-cities','global-surveillance-grid','rfid-surveillance'] },
  { slug: 'neuromarketing',        title: 'Neuromarketing — fMRI and EEG Used to Bypass Conscious Choice', section: 'Technology Control', mapBadge: 'Technology', keywords: ['neuromarketing','fMRI','EEG','consumer manipulation','subconscious advertising'], relatedSlugs: ['tavistock-institute','kill-your-tv','social-media-control','mkultra'] },
  { slug: 'dream-data-mining',     title: 'Dream Data Mining — Dormio Device, DARPA Sleep Research',  section: 'Technology Control', mapBadge: 'Technology', keywords: ['Dormio','dream hacking','DARPA','sleep research','hypnagogia','MIT'], relatedSlugs: ['mkultra','transhumanism','super-soldiers','voice-of-god-tech'] },
  { slug: 'digital-twin-humans',   title: 'Digital Twin Humans — Full Behavioral Simulation per Citizen', section: 'Technology Control', mapBadge: 'Technology', keywords: ['digital twin','behavioural simulation','smart city','AI surveillance','control grid'], relatedSlugs: ['smart-cities','ai-surveillance','cbdc','global-surveillance-grid'] },
  { slug: 'machine-prophets',      title: 'Machine Prophets — AI Systems Given Predictive Authority',  section: 'Technology Control', mapBadge: 'Technology', keywords: ['AI prediction','algorithmic authority','machine learning governance','pre-crime'], relatedSlugs: ['predictive-policing','ai-surveillance','hegelian-dialectic','transhumanism'] },
  { slug: 'pegasus-spyware',       title: 'Pegasus Spyware — NSO Group, 50,000 Phones, Journalists and Leaders', section: 'Technology Control', mapBadge: 'Surveillance', keywords: ['Pegasus','NSO Group','spyware','journalists','world leaders','zero-click'], relatedSlugs: ['nsa-surveillance','five-eyes','global-surveillance-grid','snowden-assange'] },
  { slug: 'clearview-ai',          title: 'Clearview AI — 30 Billion Scraped Faces, No Consent',     section: 'Technology Control', mapBadge: 'Surveillance', keywords: ['Clearview AI','facial recognition','scraping','biometrics','police'], relatedSlugs: ['ai-surveillance','global-surveillance-grid','emotion-recognition','nsa-surveillance'] },
  { slug: 'palantir-gotham',       title: 'Palantir Gotham — The Surveillance Ontology Behind Police AI', section: 'Technology Control', mapBadge: 'Surveillance', keywords: ['Palantir','Gotham','police AI','Peter Thiel','surveillance capitalism'], relatedSlugs: ['ai-surveillance','predictive-policing','in-q-tel','global-surveillance-grid'] },
  { slug: 'brain-computer-patents', title: 'Brain-Computer Telemetry Patents — Neuralink and Classified Variants', section: 'Technology Control', mapBadge: 'Technology', keywords: ['Neuralink','BCI','brain-computer interface','DARPA','classified patents'], relatedSlugs: ['transhumanism','super-soldiers','voice-of-god-tech','dream-data-mining'] },
  { slug: 'geofencing-warrants',   title: 'Geofencing Warrants — Google Giving Police Everyone Near a Crime', section: 'Technology Control', mapBadge: 'Surveillance', keywords: ['geofencing warrants','Google','police','location data','privacy'], relatedSlugs: ['nsa-surveillance','rfid-surveillance','ai-surveillance','stingray-devices'] },
  { slug: 'dead-internet-theory',  title: 'Dead Internet Theory — Most Content Is Bots, Human Web Is Dead', section: 'Technology Control', mapBadge: 'Technology', keywords: ['dead internet theory','bots','AI content','fake web','astroturfing'], relatedSlugs: ['social-media-control','ai-narrative-manipulation','synthetic-influencers','operation-mockingbird'] },

  // F. INTERNET MYSTERIES
  { slug: 'cicada-3301',           title: 'Cicada 3301 — The Impossible Puzzle, Who Ran It',          section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Cicada 3301','internet puzzle','cryptography','anonymous','dark web'], relatedSlugs: ['anonymous-meme-wars','dark-web','cia-operations','cryptography'] },
  { slug: 'lake-city-quiet-pills', title: "Lake City Quiet Pills — Reddit's Accidental Hitman Forum", section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Lake City Quiet Pills','Reddit','hitman','mercenary','dark web'], relatedSlugs: ['dark-web','cia-operations','cia-drug-trafficking','anonymous-meme-wars'] },
  { slug: 'elsagate',              title: 'Elsagate — Algorithmically Generated Child Trauma Content', section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Elsagate','YouTube Kids','child trauma content','algorithm','MKUltra'], relatedSlugs: ['disney-programming','mkultra','hollywood-satanism','adrenochrome'] },
  { slug: 'hidden-wikipedia-wars', title: 'Hidden Wikipedia Wars — The Edit Battles That Reveal Control', section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Wikipedia','edit wars','editorial control','agenda','information suppression'], relatedSlugs: ['operation-mockingbird','social-media-control','ai-narrative-manipulation','memory-holing'] },
  { slug: 'search-suppression',    title: 'Search Engine Suppression — What Google Buries and Why',   section: 'Internet Mysteries', mapBadge: 'Surveillance', keywords: ['Google suppression','search censorship','SEO manipulation','information control'], relatedSlugs: ['facebook-google-surveillance','operation-mockingbird','social-media-control','in-q-tel'] },
  { slug: 'memory-holing',         title: 'Memory-Holing Pages — Systematic Deletion of Inconvenient Facts', section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['memory hole','Wayback Machine','deleted pages','internet censorship','Orwell'], relatedSlugs: ['search-suppression','operation-mockingbird','social-media-control','stolen-history'] },
  { slug: 'markovian-parallax',    title: "Markovian Parallax Denigrate — Usenet's Most Mysterious Post", section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Markovian Parallax Denigrate','Usenet','mystery','1996','NSA','cipher'], relatedSlugs: ['cicada-3301','nsa-surveillance','dark-web','echelon'] },
  { slug: 'max-headroom-intrusion', title: 'Max Headroom Signal Intrusion 1987 — Still Unsolved',     section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Max Headroom','signal intrusion','1987','Chicago','TV piracy','unsolved'], relatedSlugs: ['media-control','horror-signal','false-flags','anonymous-meme-wars'] },
  { slug: 'dyatlov-pass',          title: 'Dyatlov Pass Incident — 9 Dead, Soviet Secret, 2021 Classified Docs', section: 'Internet Mysteries', mapBadge: 'Mystery', keywords: ['Dyatlov Pass','1959','Soviet','mysterious deaths','classified documents','Russia'], relatedSlugs: ['missing-411','alaska-triangle','skinwalker-ranch','haarp'] },

  // G. SYMBOLISM / OCCULT ARCHITECTURE
  { slug: 'denver-airport-murals', title: 'Denver Airport Murals — The Apocalyptic Artwork Explained', section: 'Symbolism', mapBadge: 'Symbols',  keywords: ['Denver Airport','murals','apocalyptic art','new world order','gargoyle'], relatedSlugs: ['obelisks-pine-cones','washington-dc','olympic-ceremonies','predictive-programming'] },
  { slug: 'masonic-street-grids',  title: 'Masonic Street Grids — DC, Paris, London Pentagram Layouts', section: 'Symbolism', mapBadge: 'Symbols', keywords: ['Masonic street grid','pentagram','Washington DC','Paris','London','Freemasonry'], relatedSlugs: ['freemasonry','washington-dc','city-of-london','obelisks-pine-cones'] },
  { slug: 'capitol-dome-symbolism', title: 'Capitol Dome Symbolism — The Apotheosis of Washington Decoded', section: 'Symbolism', mapBadge: 'Symbols', keywords: ['Capitol dome','Apotheosis of Washington','occult symbolism','Constantino Brumidi','Freemasonry'], relatedSlugs: ['freemasonry','washington-dc','masonic-street-grids','luciferian-doctrine'] },
  { slug: 'olympic-ceremonies',    title: 'Olympic Ceremony Symbolism — London 2012, Paris 2024 Decoded', section: 'Symbolism', mapBadge: 'Symbols', keywords: ['Olympic ceremonies','Illuminati symbolism','London 2012','Paris 2024','occult ritual'], relatedSlugs: ['predictive-programming','cern-occult','obelisks-pine-cones','bohemian-grove'] },
  { slug: 'currency-hidden-symbols', title: 'Currency Hidden Symbols — Dollar Bill, Euro, Pound Decoded', section: 'Symbolism', mapBadge: 'Symbols', keywords: ['dollar bill','eye of providence','pyramid','currency symbolism','Illuminati'], relatedSlugs: ['freemasonry','illuminati','federal-reserve','babylonian-money-magic'] },

  // H. MISSING PERSONS / ANOMALOUS ZONES
  { slug: 'missing-411',           title: 'Missing 411 — David Paulides NPS Clustering Data',         section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Missing 411','David Paulides','National Parks','disappearances','clusters'], relatedSlugs: ['alaska-triangle','skinwalker-ranch','bennington-triangle','dumbs'] },
  { slug: 'alaska-triangle',       title: 'Alaska Triangle — More Disappearances per Capita Than Anywhere', section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Alaska Triangle','disappearances','Nick Begich','UFOs','anomalous zone'], relatedSlugs: ['missing-411','bermuda-triangle','haarp','dyatlov-pass'] },
  { slug: 'bridgewater-triangle',  title: 'Bridgewater Triangle — Massachusetts Paranormal Hot-Zone',  section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Bridgewater Triangle','Massachusetts','paranormal','UFOs','cryptids'], relatedSlugs: ['skinwalker-ranch','missing-411','bermuda-triangle','bennington-triangle'] },
  { slug: 'skinwalker-ranch',      title: 'Skinwalker Ranch — DIA NIDS Study, Classified Findings',   section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Skinwalker Ranch','Utah','DIA','NIDS','Robert Bigelow','paranormal'], relatedSlugs: ['missing-411','alaska-triangle','haarp','portals-stargates'] },
  { slug: 'hoia-baciu',            title: "Hoia Baciu Forest — Romania's Bermuda Triangle",           section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Hoia Baciu','Romania','Bermuda Triangle','paranormal','UFOs'], relatedSlugs: ['bermuda-triangle','skinwalker-ranch','missing-411','hessdalen-lights'] },
  { slug: 'bermuda-triangle',      title: 'Bermuda Triangle Case Clusters — The Real Documented Cases', section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Bermuda Triangle','disappearances','Flight 19','USS Cyclops','methane hydrates'], relatedSlugs: ['alaska-triangle','hoia-baciu','dragons-triangle','missing-411'] },
  { slug: 'bennington-triangle',   title: 'Bennington Triangle — 5 Disappearances, 1945–50, Vermont', section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Bennington Triangle','Vermont','1945','disappearances','Paula Welden'], relatedSlugs: ['missing-411','bridgewater-triangle','alaska-triangle','skinwalker-ranch'] },
  { slug: 'zone-of-silence',       title: 'Zone of Silence Mexico — Radio Blackout, Meteorite Cluster', section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Zone of Silence','Mexico','radio blackout','meteorites','Zona del Silencio'], relatedSlugs: ['bermuda-triangle','haarp','skinwalker-ranch','firmament'] },
  { slug: 'nahanni-valley',        title: "Nahanni Valley — The 'Headless Valley' Disappearances",    section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Nahanni Valley','Canada','headless bodies','disappearances','anomalous zone'], relatedSlugs: ['missing-411','alaska-triangle','bennington-triangle','bermuda-triangle'] },
  { slug: 'oak-island',            title: 'Oak Island Deaths and Curse — The $10M Money Pit',         section: 'Anomalous Zones', mapBadge: 'Mystery', keywords: ['Oak Island','money pit','Templar treasure','Nova Scotia','curse'], relatedSlugs: ['knights-templar','bohemian-grove','missing-411','priory-of-sion'] },

  // I. FORENSIC / UNSOLVED MYSTERIES
  { slug: 'isdal-woman',           title: "Isdal Woman 1970 — Europe's Most Mysterious Death",         section: 'Forensic Mysteries', mapBadge: 'Mystery', keywords: ['Isdal Woman','Norway','1970','unidentified','spy','cold case'], relatedSlugs: ['somerton-man','jennifer-fairgate','lead-masks-case','dyatlov-pass'] },
  { slug: 'somerton-man',          title: 'Somerton Man — The Tamam Shud Cipher, Still Unsolved',     section: 'Forensic Mysteries', mapBadge: 'Mystery', keywords: ['Somerton Man','Tamam Shud','cipher','Australia','1948','unidentified'], relatedSlugs: ['isdal-woman','jennifer-fairgate','cicada-3301','dyatlov-pass'] },
  { slug: 'jennifer-fairgate',     title: 'Jennifer Fairgate — Oslo Hotel, No Identity, Disputed Ruling', section: 'Forensic Mysteries', mapBadge: 'Mystery', keywords: ['Jennifer Fairgate','Oslo','unidentified','spy','hotel death'], relatedSlugs: ['isdal-woman','somerton-man','lead-masks-case','dyatlov-pass'] },
  { slug: 'lead-masks-case',       title: 'Lead Masks Case — Two Dead Brazilians in Radiation Suits', section: 'Forensic Mysteries', mapBadge: 'Mystery', keywords: ['lead masks','Brazil','1966','radiation suits','unexplained death','UFO'], relatedSlugs: ['isdal-woman','varginha-brazil','dyatlov-pass','somerton-man'] },

  // J. MANDELA EFFECT — SPECIFIC CASES
  { slug: 'berenstain-bears',      title: 'Berenstain Bears — The Most Documented Mass False Memory',  section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Berenstain Bears','Mandela Effect','false memory','Berenstein','timeline shift'], relatedSlugs: ['mandela-effect','simulation-theory','time-travel-temporal','montauk-project'] },
  { slug: 'fruit-of-the-loom',     title: 'Fruit of the Loom Cornucopia — The Logo That Never Was',   section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Fruit of the Loom','cornucopia','Mandela Effect','false memory','logo'], relatedSlugs: ['mandela-effect','berenstain-bears','simulation-theory','monopoly-monocle'] },
  { slug: 'monopoly-monocle',      title: "Monopoly Man Monocle — Rich Uncle Pennybags Never Had One", section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Monopoly Man','monocle','Rich Uncle Pennybags','Mandela Effect','false memory'], relatedSlugs: ['mandela-effect','berenstain-bears','fruit-of-the-loom','simulation-theory'] },
  { slug: 'curious-george-tail',   title: 'Curious George Tail — No Tail in Any Original Illustration', section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Curious George','tail','Mandela Effect','false memory','H.A. Rey'], relatedSlugs: ['mandela-effect','berenstain-bears','simulation-theory','monopoly-monocle'] },
  { slug: 'new-zealand-position',  title: 'New Zealand Map Position — Northeast vs Southeast of Australia', section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['New Zealand','Mandela Effect','map position','Australia','false memory'], relatedSlugs: ['mandela-effect','flat-earth-overview','simulation-theory','berenstain-bears'] },
  { slug: 'we-are-the-champions',  title: "We Are the Champions Ending — Freddie Mercury's Missing Final Line", section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Queen','We Are the Champions','Mandela Effect','Freddie Mercury','missing lyric'], relatedSlugs: ['mandela-effect','music-industry-control','simulation-theory','berenstain-bears'] },
  { slug: 'mirror-mirror',         title: 'Mirror Mirror Line — "Magic Mirror" vs "Mirror Mirror"',   section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Snow White','mirror mirror','Magic Mirror','Mandela Effect','false memory'], relatedSlugs: ['mandela-effect','disney-programming','simulation-theory','berenstain-bears'] },
  { slug: 'apollo-13-quote',       title: 'Apollo 13 Quote — "Problem" vs "Had a Problem"',           section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['Apollo 13','Houston we have a problem','Mandela Effect','false memory','NASA'], relatedSlugs: ['mandela-effect','moon-landing','nasa-deceptions','simulation-theory'] },
  { slug: 'c3po-silver-leg',       title: 'C-3PO Silver Leg — Gold All Over vs One Silver Shin',      section: 'Mandela Effect', mapBadge: 'Paranormal', keywords: ['C-3PO','silver leg','Star Wars','Mandela Effect','false memory'], relatedSlugs: ['mandela-effect','simulation-theory','predictive-programming','berenstain-bears'] },

  // K. SECRET SCIENCE DEVICES
  { slug: 'hutchison-effect',      title: 'Hutchison Effect — Metal Levitation and Melting via EM Fields', section: 'Secret Science', mapBadge: 'Technology', keywords: ['Hutchison Effect','John Hutchison','levitation','EM fields','free energy'], relatedSlugs: ['antigravity','scalar-weapons','tesla-suppressed','biefeld-brown'] },
  { slug: 'meyer-water-fuel',      title: 'Stanley Meyer Water Fuel Cell — Patent, Demo, Mysterious Death', section: 'Secret Science', mapBadge: 'Technology', keywords: ['Stanley Meyer','water fuel cell','free energy','hydrogen','mysterious death'], relatedSlugs: ['cancer-cure-suppressed','antigravity','tesla-suppressed','cold-fusion-wars'] },
  { slug: 'biefeld-brown',         title: 'Biefeld-Brown Effect — Electrogravitic Lift, Documented in Patents', section: 'Secret Science', mapBadge: 'Technology', keywords: ['Biefeld-Brown','electrogravitics','T.T. Brown','antigravity','USAF patents'], relatedSlugs: ['antigravity','hutchison-effect','electrogravitics','tr3b-arvs'] },
  { slug: 'cold-fusion-wars',      title: 'Cold Fusion Replication Wars — Pons/Fleischmann, LENR Today', section: 'Secret Science', mapBadge: 'Technology', keywords: ['cold fusion','LENR','Pons Fleischmann','free energy','suppressed science'], relatedSlugs: ['meyer-water-fuel','cancer-cure-suppressed','rife-machine','tesla-suppressed'] },
  { slug: 'salvatore-pais-patents', title: 'Salvatore Pais Patent Cluster — US Navy Filed These, They Are Real', section: 'Secret Science', mapBadge: 'Technology', keywords: ['Salvatore Pais','US Navy patents','UFO technology','high energy electromagnetic field','hybrid aerospace vehicle'], relatedSlugs: ['tr3b-arvs','antigravity','ufo-disclosure','biefeld-brown'] },
  { slug: 'kozyrev-mirrors',       title: "Kozyrev Mirrors — Russian Consciousness-Focusing Experiments", section: 'Secret Science', mapBadge: 'Technology', keywords: ['Kozyrev mirrors','Russian experiments','consciousness','torsion fields','Nikolai Kozyrev'], relatedSlugs: ['scalar-weapons','global-consciousness','morphic-resonance','remote-viewing'] },
  { slug: 'vortex-mathematics',    title: "Vortex Mathematics — Marko Rodin's Base-9 Torus Pattern",  section: 'Secret Science', mapBadge: 'Technology', keywords: ['Vortex mathematics','Marko Rodin','torus','base-9','free energy'], relatedSlugs: ['sacred-geometry','tesla-suppressed','schumann-resonance','scalar-weapons'] },
  { slug: 'morphic-resonance',     title: 'Morphic Resonance — Rupert Sheldrake, Peer-Reviewed and Banned', section: 'Secret Science', mapBadge: 'Technology', keywords: ['morphic resonance','Rupert Sheldrake','banned science','morphogenetic fields','consciousness'], relatedSlugs: ['global-consciousness','kozyrev-mirrors','law-of-one','schumann-resonance'] },
  { slug: 'global-consciousness',  title: 'Global Consciousness Project — RNG Anomalies on 9/11 and COVID', section: 'Secret Science', mapBadge: 'Technology', keywords: ['Global Consciousness Project','RNG','random number generators','9/11 anomaly','Princeton'], relatedSlugs: ['morphic-resonance','schumann-resonance','maharishi-effect','9-11-inside-job'] },
  { slug: 'electrogravitics',      title: "Electrogravitics — T.T. Brown's Classified Programme",     section: 'Secret Science', mapBadge: 'Technology', keywords: ['electrogravitics','T.T. Brown','antigravity','classified','1956 Jane report'], relatedSlugs: ['biefeld-brown','antigravity','salvatore-pais-patents','hutchison-effect'] },
];

// ── Merge into existing queue ─────────────────────────────────────────────────
const added = [];
NEW_TOPICS.forEach((t, i) => {
  if (existingSlugs.has(t.slug)) {
    console.log(`  SKIP (exists): ${t.slug}`);
    return;
  }
  existing.push({
    id: 'auto-' + String(existing.length + 1).padStart(3, '0'),
    slug: t.slug,
    title: t.title,
    category: 'great-awakening',
    section: t.section,
    mapBadge: t.mapBadge || 'General',
    keywords: t.keywords || [],
    relatedSlugs: t.relatedSlugs || [],
    published: false
  });
  existingSlugs.add(t.slug);
  added.push(t.slug);
});

fs.writeFileSync(QUEUE_FILE, JSON.stringify(existing, null, 2), 'utf8');
console.log(`\nDone. Added ${added.length} topics. Total queue: ${existing.length}`);
